
import type { SiteContent } from './types';

export const defaultSiteContent: SiteContent = {
    global: {
        companyLogoUrl: 'https://i.imgur.com/sC0I0yF.png',
        companyProfilePdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
        mapCoordinates: {
            lat: 25.2515,
            lng: 55.3477
        },
        socialMediaLinks: {
            whatsapp: 'https://wa.me/971556663940',
            instagram: '#',
            facebook: '#',
        },
        galleryProjects: [
            { id: 1, title: 'G+P+6 Mixed Use Building', category: 'Buildings', location: 'Wadi Al Safa 5, Dubai', coverImageUrl: 'https://picsum.photos/600/400?random=21', imageUrls: ['https://picsum.photos/1200/800?random=21', 'https://picsum.photos/1200/800?random=121', 'https://picsum.photos/1200/800?random=221'] },
            { id: 2, title: 'Residential Commercial Building (GF+P+3+R)', category: 'Buildings', location: 'Dubai', coverImageUrl: 'https://picsum.photos/600/500?random=22', imageUrls: ['https://picsum.photos/1200/800?random=22', 'https://picsum.photos/1200/800?random=122', 'https://picsum.photos/1200/800?random=222'] },
            { id: 3, title: 'Proposed B+G+1 Showroom', category: 'Buildings', location: 'Al Barsha 3, Dubai', coverImageUrl: 'https://picsum.photos/600/350?random=23', imageUrls: ['https://picsum.photos/1200/800?random=23', 'https://picsum.photos/1200/800?random=123', 'https://picsum.photos/1200/800?random=223'] },
            { id: 5, title: 'B+G+1 Villa', category: 'Villas', location: 'Nad Al Sheba 4th, Dubai', coverImageUrl: 'https://picsum.photos/600/550?random=25', imageUrls: ['https://picsum.photos/1200/800?random=25', 'https://picsum.photos/1200/800?random=125', 'https://picsum.photos/1200/800?random=225'] },
            { id: 6, title: 'Proposed G+M+R', category: 'Villas', location: 'Nad Al Sheba, Dubai', coverImageUrl: 'https://picsum.photos/600/420?random=26', imageUrls: ['https://picsum.photos/1200/800?random=26', 'https://picsum.photos/1200/800?random=126', 'https://picsum.photos/1200/800?random=226'] },
            { id: 7, title: 'Proposed G+1+Roof Villa & Compound Wall', category: 'Villas', location: 'Al Warqa 3rd, Dubai', coverImageUrl: 'https://picsum.photos/600/480?random=27', imageUrls: ['https://picsum.photos/1200/800?random=27', 'https://picsum.photos/1200/800?random=127', 'https://picsum.photos/1200/800?random=227'] },
            { id: 8, title: 'G+1+Roof Twin Villa and Compound Wall', category: 'Villas', location: 'Umm Suqeim, Dubai', coverImageUrl: 'https://picsum.photos/600/410?random=28', imageUrls: ['https://picsum.photos/1200/800?random=28', 'https://picsum.photos/1200/800?random=128', 'https://picsum.photos/1200/800?random=228'] },
            { id: 9, title: 'Renovation of G+1 Villa', category: 'Villas', location: 'Dubai', coverImageUrl: 'https://picsum.photos/600/430?random=29', imageUrls: ['https://picsum.photos/1200/800?random=29', 'https://picsum.photos/1200/800?random=129', 'https://picsum.photos/1200/800?random=229'] },
            { id: 10, title: 'Proposed G+1+Roof Villa', category: 'Villas', location: 'Al Barsha Second, Dubai', coverImageUrl: 'https://picsum.photos/600/460?random=30', imageUrls: ['https://picsum.photos/1200/800?random=30', 'https://picsum.photos/1200/800?random=130', 'https://picsum.photos/1200/800?random=230'] },
        ],
        teamMembers: [
            { id: 6, imageUrl: 'https://picsum.photos/400/400?random=6' },
            { id: 5, imageUrl: 'https://picsum.photos/400/400?random=5' },
            { id: 4, imageUrl: 'https://picsum.photos/400/400?random=4' },
        ],
        teamPhotos: [
            { id: 1, title: 'Team Meeting On-Site', imageUrl: 'https://picsum.photos/600/450?random=501' },
            { id: 2, title: 'Foundation Work in Progress', imageUrl: 'https://picsum.photos/600/400?random=502' },
            { id: 3, title: 'Final Touches on a Villa', imageUrl: 'https://picsum.photos/600/500?random=503' },
            { id: 4, title: 'Engineers Reviewing Blueprints', imageUrl: 'https://picsum.photos/600/350?random=504' },
            { id: 5, title: 'Safety Inspection', imageUrl: 'https://picsum.photos/600/550?random=505' },
            { id: 6, title: 'Celebrating Project Completion', imageUrl: 'https://picsum.photos/600/420?random=506' },
        ],
        services: [
          { key: 'building_construction', iconKey: 'building_construction' },
          { key: 'villa_construction', iconKey: 'villa_construction' },
          { key: 'quality', iconKey: 'quality' },
          { key: 'safety_health', iconKey: 'safety_health' },
          { key: 'environment', iconKey: 'environment' },
        ],
        coreValues: [
            { key: 'quality', iconKey: 'quality_value' },
            { key: 'safety', iconKey: 'safety_value' },
            { key: 'punctuality', iconKey: 'punctuality_value' },
            { key: 'transparency', iconKey: 'transparency_value' },
            { key: 'innovation', iconKey: 'innovation_value' },
        ]
    },
    en: {
        general: {
            heroTitle: 'Model House Building Contracting',
            heroSubtitle: 'We execute high-quality residential and commercial projects and finishes, with a professional engineering team committed to time and specifications from the first plan to the last stone.',
            homeAboutTitle: 'Who We Are',
            homeAboutDesc: 'For over a decade, Model House has been contributing to the construction of exceptional projects in the UAE. We combine deep engineering expertise with a strict commitment to quality and safety standards, ensuring every project is delivered beyond our clients\' expectations, while adhering to the agreed budget and timeline.',
            counterProjects: 'Projects Completed',
            counterClients: 'Trusted Clients',
            counterExperience: 'Years of Experience',
            homeServicesTitle: 'Our Services',
            homeServicesSubtitle: 'Integrated solutions to meet all construction and building needs.',
            homeProjectsCta: 'View All Projects',
            homeValuesTitle: 'Our Vision & Values',
            homeValuesSubtitle: 'The principles that guide every decision we make and every stone we lay.',
            homeTeamTitle: 'Management Team',
            homeTeamSubtitle: 'The expertise that drives our success.',
            homeCtaTitle: 'Ready to start your project with Model House?',
            homeCtaSubtitle: 'Leave your details, and a specialized engineer will contact you to propose the best solution for your project and budget.',
            homeCtaButton: 'Contact Us Now',
            footerTagline: 'Your trusted partner for safe construction and investment in the United Arab Emirates.',
            footerAddress: 'Flower of Garhoud Building, 2nd St, Garhoud, Dubai',
            aboutPageTitle: 'About Model House',
            aboutPageSubtitle: 'Building the future with engineering quality and safety.',
            aboutIntroTitle: 'Introduction',
            aboutIntroDesc: 'Model House Contracting is a forward-thinking, active, and dynamic construction company. We add value by achieving optimal results for both owners and tenants who love to transform their properties and achieve maximum financial returns. Executing fit-out, renovation, and construction projects is what we do. Our philosophy is that all successful projects are based on the people responsible for the project, and our team is dedicated to understanding our clients\' business objectives so they can create buildings that meet their needs.',
            aboutVisionTitle: 'Our Vision',
            aboutVisionDesc: 'To be the preferred contractor in the construction and industrial sector.',
            aboutMissionTitle: 'Our Mission',
            aboutMission1: 'To provide high-quality work and reliable services at reasonable prices.',
            aboutMission2: 'To form strategic alliances with established companies and key industry figures.',
            aboutMission3: 'To create awareness of the potential of construction and building solutions.',
            aboutChairmanTitle: 'LETTER FROM CHAIRMAN',
            aboutChairmanName: 'M. Salama Mansour',
            aboutChairmanPosition: 'Chairman',
            aboutChairmanMessage: "Model House Building Contracting has always had a vision set on leadership in all our operations and this has been realized through an emphasis on customer centric approach. The performance based on leadership adopted by our company has enabled us to face many challenges over the years and in effect has strengthen our foundation.We are in the process of expanding and introducing new services. A commitment to quality together with well-designed & competitively priced services has provided the backbone to M.H'S success and the formula will continue to meet our customer's approval. I would like to take this opportunity to extend my deep appreciation to our business associates and customers for their continued faith in the company and its management. I would also like to thank our management I would also like to thank our management team for their support and continued determination to grow with us through these challenging times. I would also like to thank our staff for their dedication and commitment to work with us and building a strong foundation to sustain and improve the company's performance",
            aboutTeamTitle: 'Leadership Team',
            aboutTeamSubtitle: 'The driving force behind our success is our team of dedicated and experienced professionals.',
            aboutQhseTitle: 'Quality, Health, Safety & Environment (QHSE) Management',
            aboutQhseSubtitle: 'Our commitment to the highest standards in every aspect of our work.',
            aboutQhseHealthTitle: 'Health & Safety',
            aboutQhseHealthDesc: 'Model House Building Contracting proactively fosters a safe working environment to enhance the well-being of its employees and the communities within its areas of operation.',
            aboutQhseEnvTitle: 'Environment',
            aboutQhseEnvDesc: 'Model House Building Contracting emphasizes environmental awareness in everything it does. It is keenly aware of the impact its operations & projects may have on the environment, and as a result, implements programs and policies to minimize adverse effects focusing on construction methods and materials that allow for a greener project construction process.',
            aboutQhseQualityTitle: 'Quality',
            aboutQhseQualityDesc: 'Model House Building Contracting divisions are accredited & audited by industry bodies in line with industry standards & requirements. The group implements intensive development and training programs in an effort to constantly raise its performance & set standards at the level it considers in keeping with its approach of delivering quality products to its clients.',
            contactPageTitle: 'Contact Us',
            contactPageSubtitle: 'We are here to answer all your inquiries. Contact us, and we will get back to you as soon as possible.',
            contactInfoTitle: 'Contact Information',
            contactWorkingHoursTitle: 'Working Hours',
            contactPhone1: '+971 55 666 3940 / +971 55 503 6841',
            contactPhone2: '+971 4 558 5407',
            contactEmail: 'info@modelhs.com',
            profilePageTitle: 'Company Profile',
            profilePageSubtitle: 'View our official company profile document below.',
        },
        services: [
            { key: 'building_construction', title: 'Building Construction', description: 'We specialize in constructing various types of residential and commercial buildings, adhering to the highest standards of quality and modern design to meet our clients\' needs.' },
            { key: 'villa_construction', title: 'Villa Construction', description: 'Designing and executing luxury residential villas with modern designs and high-quality finishes. We turn your dream home into a reality.' },
            { key: 'quality', title: 'Quality', description: 'Model House Building Contracting divisions are accredited and audited by industry bodies in line with industry standards and requirements. The group implements intensive development and training programs in an effort to constantly raise its performance and set standards at the level it considers in keeping with its approach of delivering quality products to its clients.' },
            { key: 'safety_health', title: 'Safety & Health', description: 'Model House Building Contracting proactively fosters a safe working environment to enhance the well-being of its employees and the communities within its areas of operation.' },
            { key: 'environment', title: 'Environment', description: 'Model House Building Contracting emphasizes environmental awareness in everything it does. It is keenly aware of the impact its operations and projects may have on the environment and, as a result, implements programs and policies to minimize adverse effects focusing on construction methods and materials that allow for a greener project construction process.' },
        ],
        coreValues: [
            { key: 'quality', title: 'Quality First', description: 'We use the best materials and apply the highest engineering standards to ensure a lasting construction.' },
            { key: 'safety', title: 'Safety Above All', description: 'The safety of our teams and sites is a top priority we never compromise on.' },
            { key: 'punctuality', title: 'Commitment to Deadlines', description: 'We respect your time and investment, delivering projects within the agreed-upon schedule.' },
            { key: 'transparency', title: 'Transparency with the Client', description: 'We keep you informed of all project stages with clarity and honesty.' },
            { key: 'innovation', title: 'Innovation in Solutions', description: 'We are always seeking the latest technologies and engineering solutions to deliver the best.' },
        ],
        teamMembers: [
            { id: 6, name: 'Eng. Mohamed Salama', title: 'Executive Director', bio: 'Drives the company\'s vision and strategy, overseeing all executive decisions and operational management.' },
            { id: 5, name: 'Eng. Mohamed Zuhaib', title: 'Projects Manager', bio: 'Leads project execution from start to finish, ensuring alignment with client goals and company standards.' },
            { id: 4, name: 'Mahmoud Badawy', title: 'Accounts Manager', bio: 'Manages financial planning and accounting operations, ensuring fiscal responsibility and efficiency.' },
        ],
        workingHours: [
            { id: 1, day: 'Monday', time: '8:00 AM — 5:00 PM' },
            { id: 2, day: 'Tuesday', time: '8:00 AM — 5:00 PM' },
            { id: 3, day: 'Wednesday', time: '8:00 AM — 5:00 PM' },
            { id: 4, day: 'Thursday', time: '8:00 AM — 5:00 PM' },
            { id: 5, day: 'Friday', time: '8:00 AM — 5:00 PM' },
            { id: 6, day: 'Saturday', time: '8:00 AM — 5:00 PM' },
            { id: 7, day: 'Sunday', time: 'OFF' },
        ]
    },
    ar: {
        general: {
            heroTitle: 'Model house building contracting',
            heroSubtitle: 'ننفّذ مشاريع سكنية وتجارية وتشطيبات عالية الجودة، مع فريق هندسي محترف يلتزم بالوقت والمواصفات من أول مخطط لآخر حجر.',
            homeAboutTitle: 'من نحن',
            homeAboutDesc: 'لأكثر من عقد من الزمان، تساهم موديل هاوس في بناء مشاريع استثنائية في الإمارات. نحن نجمع بين الخبرة الهندسية العريقة والالتزام الصارم بمعايير الجودة والأمان، لنضمن تسليم كل مشروع بما يفوق توقعات عملائنا، مع الحفاظ على الميزانية والجدول الزمني المتفق عليه.',
            counterProjects: 'مشروع منجز',
            counterClients: 'عميل موثوق',
            counterExperience: 'سنوات خبرة',
            homeServicesTitle: 'خدماتنا',
            homeServicesSubtitle: 'حلول متكاملة لتلبية كافة احتياجات البناء والتشييد.',
            homeProjectsCta: 'عرض جميع المشاريع',
            homeValuesTitle: 'رؤيتنا وقيمنا',
            homeValuesSubtitle: 'المبادئ التي توجه كل قرار نتخذه وكل حجر نضعه.',
            homeTeamTitle: 'فريق الإدارة',
            homeTeamSubtitle: 'الخبرة التي تقود نجاحنا.',
            homeCtaTitle: 'جاهز لتبدأ مشروعك مع موديل هاوس؟',
            homeCtaSubtitle: 'اترك بياناتك وسيتواصل معك مهندس مختص ليقترح أفضل حل لمشروعك وميزانيتك.',
            homeCtaButton: 'تواصل معنا الآن',
            footerTagline: 'شريكك الموثوق لبناء واستثمار آمن في الإمارات العربية المتحدة.',
            footerAddress: 'بناية زهرة القرهود - شارع ٢ - القرهود - دبي',
            aboutPageTitle: 'عن موديل هاوس',
            aboutPageSubtitle: 'نبني المستقبل بجودة وأمان هندسي.',
            aboutIntroTitle: 'مقدمة',
            aboutIntroDesc: 'شركة موديل هاوس للمقاولات هي شركة إنشاءات ذات تفكير تقدمي، نشطة وديناميكية. نحن نضيف قيمة من خلال تحقيق نتائج مثالية لكل من الملاك والمستأجرين، حيث يحبون تحويل ممتلكاتهم وتحقيق أقصى العوائد المالية. تنفيذ مشاريع التجهيز، التجديد، والإنشاءات هو ما نقوم به. فلسفتنا هي أن جميع المشاريع الناجحة تعتمد على الأشخاص المسؤولين عن المشروع، وفريقنا مكرس لفهم أهداف عملائنا التجارية حتى يتمكنوا من إنشاء مبانٍ تلبي احتياجاتهم.',
            aboutVisionTitle: 'رؤيتنا',
            aboutVisionDesc: 'أن نكون المقاول المفضل في قطاع البناء والصناعة.',
            aboutMissionTitle: 'رسالتنا',
            aboutMission1: 'تقديم أعمال عالية الجودة وخدمات موثوقة بأسعار معقولة.',
            aboutMission2: 'عقد تحالف استراتيجي مع شركات راسخة وشخصيات رئيسية في الصناعة.',
            aboutMission3: 'خلق وعي بإمكانيات حلول البناء والتشييد.',
            aboutChairmanTitle: 'رسالة من رئيس مجلس الإدارة',
            aboutChairmanName: 'م. سلامة منصور',
            aboutChairmanPosition: 'رئيس مجلس الإدارة',
            // FIX: Removed extra single quote from the key 'aboutChairmanMessage''
            aboutChairmanMessage: 'لطالما كانت لدى شركة موديل هاوس للمقاولات رؤية ترتكز على الريادة في جميع عملياتنا، وقد تحقق ذلك من خلال التركيز على نهج يضع العملاء في المقام الأول. إن الأداء القائم على القيادة الذي تتبناه شركتنا قد مكّننا من مواجهة العديد من التحديات على مر السنين، وساهم في تقوية أسسنا. نحن الآن في طور التوسع وتقديم خدمات جديدة. إن الالتزام بالجودة، إلى جانب الخدمات المصممة جيدًا وبأسعار تنافسية، قد شكّل العمود الفقري لنجاح موديل هاوس، وستستمر هذه الصيغة في نيل رضا عملائنا. أود أن أغتنم هذه الفرصة لأعرب عن عميق تقديري لشركائنا في العمل وعملائنا على ثقتهم المستمرة في الشركة وإدارتها. كما أود أن أشكر فريق إدارتنا على دعمهم وعزيمتهم المستمرة للنمو معنا خلال هذه الأوقات الصعبة. وأود أيضًا أن أشكر موظفينا على تفانيهم والتزامهم بالعمل معنا وبناء أساس قوي للحفاظ على أداء الشركة وتحسينه.',
            aboutTeamTitle: 'فريق القيادة',
            aboutTeamSubtitle: 'القوة الدافعة وراء نجاحنا هي فريقنا من المهنيين المتفانين وذوي الخبرة.',
            aboutQhseTitle: 'إدارة الجودة والصحة والسلامة والبيئة',
            aboutQhseSubtitle: 'التزامنا بأعلى المعايير في كل جانب من جوانب عملنا.',
            aboutQhseHealthTitle: 'السلامة والصحة',
            aboutQhseHealthDesc: 'تعمل شركة موديل هاوس للمقاولات بشكل استباقي على تعزيز بيئة عمل آمنة لتعزيز رفاهية موظفيها والمجتمعات داخل مناطق عملياتها.',
            aboutQhseEnvTitle: 'البيئة',
            aboutQhseEnvDesc: 'تؤكد شركة موديل هاوس للمقاولات على الوعي البيئي في كل ما تقوم به. وهي تدرك تمامًا التأثير الذي قد تحدثه عملياتها ومشاريعها على البيئة، ونتيجة لذلك، تنفذ برامج وسياسات لتقليل الآثار السلبية، مع التركيز على أساليب ومواد البناء التي تسمح بعملية بناء مشاريع أكثر استدامة.',
            aboutQhseQualityTitle: 'الجودة',
            // FIX: Removed extra single quote from the key 'aboutQhseQualityDesc''
            aboutQhseQualityDesc: 'أقسام شركة موديل هاوس للمقاولات معتمدة ومدققة من قبل هيئات الصناعة بما يتماشى مع معايير ومتطلبات الصناعة. تنفذ المجموعة برامج تطوير وتدريب مكثفة في محاولة لرفع مستوى أدائها باستمرار ووضع المعايير بالمستوى الذي تعتبره متماشياً مع نهجها في تقديم منتجات عالية الجودة لعملائها.',
            contactPageTitle: 'تواصل معنا',
            contactPageSubtitle: 'نحن هنا للإجابة على جميع استفساراتك. تواصل معنا وسنرد عليك في أقرب وقت ممكن.',
            contactInfoTitle: 'معلومات الاتصال',
            contactWorkingHoursTitle: 'ساعات العمل',
            contactPhone1: '+971 55 666 3940 / +971 55 503 6841',
            contactPhone2: '+971 4 558 5407',
            contactEmail: 'info@modelhs.com',
            profilePageTitle: 'ملف الشركة',
            profilePageSubtitle: 'استعرض ملف الشركة الرسمي أدناه.',
        },
        services: [
            { key: 'building_construction', title: 'بناء البنايات', description: 'متخصصون في بناء مختلف أنواع المباني السكنية والتجارية، مع الالتزام بأعلى معايير الجودة والتصميم الحديث لتلبية احتياجات عملائنا.' },
            { key: 'villa_construction', title: 'بناء الفلل', description: 'تصميم وتنفيذ فلل سكنية فاخرة بتصاميم عصرية وتشطيبات عالية الجودة، نحول منزل أحلامك إلى واقع.' },
            { key: 'quality', title: 'الجودة', description: 'أقسام شركة موديل هاوس للمقاولات معتمدة ومدققة من قبل هيئات الصناعة بما يتماشى مع معايير ومتطلبات الصناعة. تنفذ المجموعة برامج تطوير وتدريب مكثفة في محاولة لرفع مستوى أدائها باستمرار ووضع المعايير بالمستوى الذي تعتبره متماشياً مع نهجها في تقديم منتجات عالية الجودة لعملائها.' },
            { key: 'safety_health', title: 'السلامة والصحة', description: 'تعمل شركة موديل هاوس للمقاولات بشكل استباقي على تعزيز بيئة عمل آمنة لتعزيز رفاهية موظفيها والمجتمعات داخل مناطق عملياتها.' },
            { key: 'environment', title: 'البيئة', description: 'تؤكد شركة موديل هاوس للمقاولات على الوعي البيئي في كل ما تقوم به. وهي تدرك تمامًا التأثير الذي قد تحدثه عملياتها ومشاريعها على البيئة، ونتيجة لذلك، تنفذ برامج وسياسات لتقليل الآثار السلبية، مع التركيز على أساليب ومواد البناء التي تسمح بعملية بناء مشاريع أكثر استدامة.' },
        ],
        coreValues: [
            { key: 'quality', title: 'الجودة أولاً', description: 'نستخدم أفضل المواد ونطبق أعلى المعايير الهندسية لضمان بناء يدوم.' },
            { key: 'safety', title: 'السلامة قبل كل شيء', description: 'سلامة فرق عملنا ومواقعنا هي أولوية قصوى لا نتنازل عنها أبدًا.' },
            { key: 'punctuality', title: 'الالتزام بالمواعيد', description: 'نحترم وقتك واستثمارك، ونسلّم المشاريع ضمن الجدول الزمني المتفق عليه.' },
            { key: 'transparency', title: 'الشفافية مع العميل', description: 'نبقيك على اطلاع دائم بجميع مراحل المشروع بوضوح وصدق.' },
            { key: 'innovation', title: 'الابتكار في الحلول', description: 'نبحث دائمًا عن أحدث التقنيات والحلول الهندسية لتقديم الأفضل.' },
        ],
        teamMembers: [
            { id: 6, name: 'م. محمد سلامة', title: 'المدير التنفيذي', bio: 'يقود رؤية الشركة واستراتيجيتها، ويشرف على جميع القرارات التنفيذية وإدارة العمليات.' },
            { id: 5, name: 'م. محمد زهيب', title: 'مدير المشاريع', bio: 'يقود تنفيذ المشاريع من البداية إلى النهاية، مما يضمن التوافق مع أهداف العميل ومعايير الشركة.' },
            { id: 4, name: 'محمود بدوي', title: 'مدير الحسابات', bio: 'يدير التخطيط المالي والعمليات المحاسبية، مما يضمن المسؤولية والكفاءة المالية.' },
        ],
        workingHours: [
            { id: 1, day: 'الإثنين', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 2, day: 'الثلاثاء', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 3, day: 'الأربعاء', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 4, day: 'الخميس', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 5, day: 'الجمعة', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 6, day: 'السبت', time: '8:00 صباحًا — 5:00 مساءً' },
            { id: 7, day: 'الأحد', time: 'مغلق' },
        ]
    },
};